//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.LocadoraDeJogos.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela INSERIRDESCONTO
    /// </summary>
    public partial interface IInserirdesconto : IEntityBase
    {
        
        /// <summary>
        /// Código desconto (CODIGODESCONTO.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string CodigoDesconto
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela INSERIRDESCONTO
    /// </summary>
    public partial interface IInserirdescontoDao : IBusinessEntityDao<IInserirdesconto>
    {
    }
    
    /// <summary>
    /// DAO para a tabela INSERIRDESCONTO
    /// </summary>
    public partial class InserirdescontoDao : BusinessEntityDao<Inserirdesconto, IInserirdesconto>, IInserirdescontoDao
    {
        
        public static InserirdescontoDao CreateInstance()
        {
            return CreateInstance<InserirdescontoDao>();
        }
    }
    
    /// <summary>
    /// Inserirdesconto
    /// </summary>
    [EntityDefinitionName("INSERIRDESCONTO")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Inserirdesconto : BusinessEntity<Inserirdesconto>, IInserirdesconto
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string CodigoDesconto = "CODIGODESCONTO";
		}

        
        /// <summary>
        /// Código desconto (CODIGODESCONTO.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string CodigoDesconto
        {
            get
            {
                return Fields["CODIGODESCONTO"] as System.String;
            }
            set
            {
                Fields["CODIGODESCONTO"] = value;
            }
        }
    }
}
