//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.LocadoraDeJogos.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela ITENSPEDIDO
    /// </summary>
    public partial interface IItenspedido : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.LocadoraDeJogos.Entidades.IPedido PedidoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle PedidoHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.LocadoraDeJogos.Entidades.IProdutos ProdutoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ProdutoHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<long> Quantidade
        {
            get;
            set;
        }
        
        /// <summary>
        /// ValorTotal (VALORTOTAL.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 100000, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Valortotal
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela ITENSPEDIDO
    /// </summary>
    public partial interface IItenspedidoDao : IBusinessEntityDao<IItenspedido>
    {
    }
    
    /// <summary>
    /// DAO para a tabela ITENSPEDIDO
    /// </summary>
    public partial class ItenspedidoDao : BusinessEntityDao<Itenspedido, IItenspedido>, IItenspedidoDao
    {
        
        public static ItenspedidoDao CreateInstance()
        {
            return CreateInstance<ItenspedidoDao>();
        }
    }
    
    /// <summary>
    /// Itenspedido
    /// </summary>
    [EntityDefinitionName("ITENSPEDIDO")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Itenspedido : BusinessEntity<Itenspedido>, IItenspedido
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Pedido = "PEDIDO";
			public const string Produto = "PRODUTO";
			public const string Quantidade = "QUANTIDADE";
			public const string Valortotal = "VALORTOTAL";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.LocadoraDeJogos.Entidades.IPedido PedidoInstance
        {
            get
            {
                if (Pedido.Handle == null)
                {
					return null;
                }
                return Pedido.Instance;
            }
            set
            {
                if (value == null)
                {
					Pedido = null;
					return;
                }
                Pedido.Instance = (Benner.LocadoraDeJogos.Entidades.Pedido) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle PedidoHandle
        {
            get
            {
                return Pedido.Handle;
            }
            set
            {
                Pedido.Handle = value;
            }
        }
        
        /// <summary>
        /// Pedido (PEDIDO.)
        /// Opcional = N, Invisível = False, Pesquisar = PEDIDO
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.LocadoraDeJogos.Entidades.Pedido> Pedido
        {
            get
            {
                return (Fields["PEDIDO"] as EntityAssociation).Wrap<Benner.LocadoraDeJogos.Entidades.Pedido>(Benner.LocadoraDeJogos.Entidades.Pedido.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Pedido.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Pedido.Instance = value.Instance;
                    }
                    else
                    {
                        this.Pedido.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.LocadoraDeJogos.Entidades.IProdutos ProdutoInstance
        {
            get
            {
                if (Produto.Handle == null)
                {
					return null;
                }
                return Produto.Instance;
            }
            set
            {
                if (value == null)
                {
					Produto = null;
					return;
                }
                Produto.Instance = (Benner.LocadoraDeJogos.Entidades.Produtos) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ProdutoHandle
        {
            get
            {
                return Produto.Handle;
            }
            set
            {
                Produto.Handle = value;
            }
        }
        
        /// <summary>
        /// Produto (PRODUTO.)
        /// Opcional = N, Invisível = False, Pesquisar = PRODUTOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.LocadoraDeJogos.Entidades.Produtos> Produto
        {
            get
            {
                return (Fields["PRODUTO"] as EntityAssociation).Wrap<Benner.LocadoraDeJogos.Entidades.Produtos>(Benner.LocadoraDeJogos.Entidades.Produtos.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Produto.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Produto.Instance = value.Instance;
                    }
                    else
                    {
                        this.Produto.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<long> Quantidade
        {
            get
            {
                return Fields["QUANTIDADE"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["QUANTIDADE"] = value;
            }
        }
        
        /// <summary>
        /// ValorTotal (VALORTOTAL.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 100000, Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Valortotal
        {
            get
            {
                return Fields["VALORTOTAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORTOTAL"] = value;
            }
        }
    }
}
