//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.LocadoraDeJogos.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela PEDIDO
    /// </summary>
    public partial interface IPedido : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.LocadoraDeJogos.Entidades.IPessoas ClienteInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle ClienteHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<System.DateTime> Data
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Tecnologia.Common.IEntityBase DescontoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle DescontoHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        PedidoStatusListaItens Status
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Valortotal
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela PEDIDO
    /// </summary>
    public partial interface IPedidoDao : IBusinessEntityDao<IPedido>
    {
    }
    
    /// <summary>
    /// DAO para a tabela PEDIDO
    /// </summary>
    public partial class PedidoDao : BusinessEntityDao<Pedido, IPedido>, IPedidoDao
    {
        
        public static PedidoDao CreateInstance()
        {
            return CreateInstance<PedidoDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo STATUS.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
    public class PedidoStatusListaItens : ListItems<PedidoStatusListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Em processamento.
        /// </summary>
        public static PedidoStatusListaItens ItemEmProcessamento;
        
        /// <summary>
        /// Valor = 2, Item = Em pagamento.
        /// </summary>
        public static PedidoStatusListaItens ItemEmPagamento;
        
        /// <summary>
        /// Valor = 3, Item = Cancelado.
        /// </summary>
        public static PedidoStatusListaItens ItemCancelado;
        
        /// <summary>
        /// Valor = 4, Item = Pago.
        /// </summary>
        public static PedidoStatusListaItens ItemPago;
        
        /// <summary>
        /// Valor = 5, Item = Finalizado.
        /// </summary>
        public static PedidoStatusListaItens ItemFinalizado;
        
		public static implicit operator PedidoStatusListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(PedidoStatusListaItens item)
		{
			return item.Index;
		}
        
        static PedidoStatusListaItens()
        {
			ItemEmProcessamento = new PedidoStatusListaItens {Index = 1, Description ="Em processamento"};
			ItemEmPagamento = new PedidoStatusListaItens {Index = 2, Description ="Em pagamento"};
			ItemCancelado = new PedidoStatusListaItens {Index = 3, Description ="Cancelado"};
			ItemPago = new PedidoStatusListaItens {Index = 4, Description ="Pago"};
			ItemFinalizado = new PedidoStatusListaItens {Index = 5, Description ="Finalizado"};

			Items.Add(ItemEmProcessamento);
			Items.Add(ItemEmPagamento);
			Items.Add(ItemCancelado);
			Items.Add(ItemPago);
			Items.Add(ItemFinalizado);

        }
    }
    
    /// <summary>
    /// Pedido
    /// </summary>
    [EntityDefinitionName("PEDIDO")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Pedido : BusinessEntity<Pedido>, IPedido
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Cliente = "CLIENTE";
			public const string Data = "DATA";
			public const string Desconto = "DESCONTO";
			public const string Status = "STATUS";
			public const string Valortotal = "VALORTOTAL";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.LocadoraDeJogos.Entidades.IPessoas ClienteInstance
        {
            get
            {
                if (Cliente.Handle == null)
                {
					return null;
                }
                return Cliente.Instance;
            }
            set
            {
                if (value == null)
                {
					Cliente = null;
					return;
                }
                Cliente.Instance = (Benner.LocadoraDeJogos.Entidades.Pessoas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle ClienteHandle
        {
            get
            {
                return Cliente.Handle;
            }
            set
            {
                Cliente.Handle = value;
            }
        }
        
        /// <summary>
        /// Cliente (CLIENTE.)
        /// Opcional = N, Invisível = False, Pesquisar = PESSOAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.LocadoraDeJogos.Entidades.Pessoas> Cliente
        {
            get
            {
                return (Fields["CLIENTE"] as EntityAssociation).Wrap<Benner.LocadoraDeJogos.Entidades.Pessoas>(Benner.LocadoraDeJogos.Entidades.Pessoas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Cliente.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Cliente.Instance = value.Instance;
                    }
                    else
                    {
                        this.Cliente.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return Fields["DATA"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATA"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.IEntityBase DescontoInstance
        {
            get
            {
                if (Desconto.Handle == null)
                {
					return null;
                }
                return Desconto.Instance;
            }
            set
            {
                if (value == null)
                {
					Desconto = null;
					return;
                }
                Desconto.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle DescontoHandle
        {
            get
            {
                return Desconto.Handle;
            }
            set
            {
                Desconto.Handle = value;
            }
        }
        
        /// <summary>
        /// Desconto (DESCONTO.)
        /// Opcional = S, Invisível = False, Pesquisar = DESCONTOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation Desconto
        {
            get
            {
                return Fields["DESCONTO"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Desconto.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Desconto.Instance = value.Instance;
                    }
                    else
                    {
                        this.Desconto.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public PedidoStatusListaItens Status
        {
            get
            {
                ListItem listItem = Fields["STATUS"] as ListItem;
				if (listItem != null)
					return new PedidoStatusListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["STATUS"] = new ListItem(value.Index, value.Description);
				else
					Fields["STATUS"] = null;
            }
        }
        
        /// <summary>
        /// Valortotal (VALORTOTAL.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Valortotal
        {
            get
            {
                return Fields["VALORTOTAL"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALORTOTAL"] = value;
            }
        }
    }
}
