//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.LocadoraDeJogos.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela PESSOAS
    /// </summary>
    public partial interface IPessoas : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Cpf
        {
            get;
            set;
        }
        
        /// <summary>
        /// DataDeNascimento (DATADENASCIMENTO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<System.DateTime> Datadenascimento
        {
            get;
            set;
        }
        
        /// <summary>
        /// E-mail (EMAIL.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string EMail
        {
            get;
            set;
        }
        
        /// <summary>
        /// Imagem (IMAGEM.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        byte[] Imagem
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Nome
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        Handle UsuarioHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela PESSOAS
    /// </summary>
    public partial interface IPessoasDao : IBusinessEntityDao<IPessoas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela PESSOAS
    /// </summary>
    public partial class PessoasDao : BusinessEntityDao<Pessoas, IPessoas>, IPessoasDao
    {
        
        public static PessoasDao CreateInstance()
        {
            return CreateInstance<PessoasDao>();
        }
    }
    
    /// <summary>
    /// Pessoas
    /// </summary>
    [EntityDefinitionName("PESSOAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Pessoas : BusinessEntity<Pessoas>, IPessoas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Cpf = "CPF";
			public const string Datadenascimento = "DATADENASCIMENTO";
			public const string EMail = "EMAIL";
			public const string Imagem = "IMAGEM";
			public const string Nome = "NOME";
			public const string Usuario = "USUARIO";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Cpf
        {
            get
            {
                return Fields["CPF"] as System.String;
            }
            set
            {
                Fields["CPF"] = value;
            }
        }
        
        /// <summary>
        /// DataDeNascimento (DATADENASCIMENTO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<System.DateTime> Datadenascimento
        {
            get
            {
                return Fields["DATADENASCIMENTO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATADENASCIMENTO"] = value;
            }
        }
        
        /// <summary>
        /// E-mail (EMAIL.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string EMail
        {
            get
            {
                return Fields["EMAIL"] as System.String;
            }
            set
            {
                Fields["EMAIL"] = value;
            }
        }
        
        /// <summary>
        /// Imagem (IMAGEM.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public byte[] Imagem
        {
            get
            {
                return Fields["IMAGEM"] as System.Byte[];
            }
            set
            {
                Fields["IMAGEM"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioInstance
        {
            get
            {
                if (Usuario.Handle == null)
                {
					return null;
                }
                return Usuario.Instance;
            }
            set
            {
                if (value == null)
                {
					Usuario = null;
					return;
                }
                Usuario.Instance = (Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Handle UsuarioHandle
        {
            get
            {
                return Usuario.Handle;
            }
            set
            {
                Usuario.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuario (USUARIO.)
        /// Opcional = N, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios> Usuario
        {
            get
            {
                return (Fields["USUARIO"] as EntityAssociation).Wrap<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios>(Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Usuario.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Usuario.Instance = value.Instance;
                    }
                    else
                    {
                        this.Usuario.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
