//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.LocadoraDeJogos.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela PRODUTOS
    /// </summary>
    public partial interface IProdutos : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// CategoriaDoProduto (CATEGORIADOPRODUTO.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Categoriadoproduto
        {
            get;
            set;
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Descricao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Imagem (IMAGEM.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        byte[] Imagem
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Observacoes (OBSERVACOES.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        string Observacoes
        {
            get;
            set;
        }
        
        /// <summary>
        /// Preço (PRECO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<decimal> Preco
        {
            get;
            set;
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        System.Nullable<long> Quantidade
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela PRODUTOS
    /// </summary>
    public partial interface IProdutosDao : IBusinessEntityDao<IProdutos>
    {
    }
    
    /// <summary>
    /// DAO para a tabela PRODUTOS
    /// </summary>
    public partial class ProdutosDao : BusinessEntityDao<Produtos, IProdutos>, IProdutosDao
    {
        
        public static ProdutosDao CreateInstance()
        {
            return CreateInstance<ProdutosDao>();
        }
    }
    
    /// <summary>
    /// Produtos
    /// </summary>
    [EntityDefinitionName("PRODUTOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Produtos : BusinessEntity<Produtos>, IProdutos
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Categoriadoproduto = "CATEGORIADOPRODUTO";
			public const string Descricao = "DESCRICAO";
			public const string Imagem = "IMAGEM";
			public const string Nome = "NOME";
			public const string Observacoes = "OBSERVACOES";
			public const string Preco = "PRECO";
			public const string Quantidade = "QUANTIDADE";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// CategoriaDoProduto (CATEGORIADOPRODUTO.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Categoriadoproduto
        {
            get
            {
                return Fields["CATEGORIADOPRODUTO"] as System.String;
            }
            set
            {
                Fields["CATEGORIADOPRODUTO"] = value;
            }
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Descricao
        {
            get
            {
                return Fields["DESCRICAO"] as System.String;
            }
            set
            {
                Fields["DESCRICAO"] = value;
            }
        }
        
        /// <summary>
        /// Imagem (IMAGEM.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public byte[] Imagem
        {
            get
            {
                return Fields["IMAGEM"] as System.Byte[];
            }
            set
            {
                Fields["IMAGEM"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 20
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Observacoes (OBSERVACOES.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public string Observacoes
        {
            get
            {
                return Fields["OBSERVACOES"] as System.String;
            }
            set
            {
                Fields["OBSERVACOES"] = value;
            }
        }
        
        /// <summary>
        /// Preço (PRECO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<decimal> Preco
        {
            get
            {
                return Fields["PRECO"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["PRECO"] = value;
            }
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "18.2.0.790")]
        public System.Nullable<long> Quantidade
        {
            get
            {
                return Fields["QUANTIDADE"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["QUANTIDADE"] = value;
            }
        }
    }
}
